/**
 * generated by Xtext 2.11.0
 */
package de.darmstadt.tu.crossing.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.darmstadt.tu.crossing.CryptSLRuntimeModule;
import de.darmstadt.tu.crossing.CryptSLStandaloneSetup;
import de.darmstadt.tu.crossing.ide.CryptSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CryptSLIdeSetup extends CryptSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    CryptSLRuntimeModule _cryptSLRuntimeModule = new CryptSLRuntimeModule();
    CryptSLIdeModule _cryptSLIdeModule = new CryptSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_cryptSLRuntimeModule, _cryptSLIdeModule));
  }
}
