/*
 * generated by Xtext 2.27.0
 */
package de.darmstadt.tu.crossing.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CrySLUiModule extends AbstractCrySLUiModule {

	public CrySLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
