/**
 * generated by Xtext 2.10.0
 */
package de.darmstadt.tu.crossing.ui.contentassist;

import de.darmstadt.tu.crossing.ui.contentassist.AbstractCryptSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CryptSLProposalProvider extends AbstractCryptSLProposalProvider {
}
