/**
 * generated by Xtext 2.13.0
 */
package de.darmstadt.tu.crossing.cryptSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparison Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getComparisonExpression()
 * @model
 * @generated
 */
public interface ComparisonExpression extends Constraint
{
} // ComparisonExpression
