/**
 * generated by Xtext 2.15.0
 */
package de.darmstadt.tu.crossing.cryptSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pre Defined Predicates</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.darmstadt.tu.crossing.cryptSL.PreDefinedPredicates#getPredName <em>Pred Name</em>}</li>
 *   <li>{@link de.darmstadt.tu.crossing.cryptSL.PreDefinedPredicates#getObj <em>Obj</em>}</li>
 *   <li>{@link de.darmstadt.tu.crossing.cryptSL.PreDefinedPredicates#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getPreDefinedPredicates()
 * @model
 * @generated
 */
public interface PreDefinedPredicates extends LiteralExpression
{
  /**
   * Returns the value of the '<em><b>Pred Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pred Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pred Name</em>' attribute.
   * @see #setPredName(String)
   * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getPreDefinedPredicates_PredName()
   * @model
   * @generated
   */
  String getPredName();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.cryptSL.PreDefinedPredicates#getPredName <em>Pred Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pred Name</em>' attribute.
   * @see #getPredName()
   * @generated
   */
  void setPredName(String value);

  /**
   * Returns the value of the '<em><b>Obj</b></em>' reference list.
   * The list contents are of type {@link de.darmstadt.tu.crossing.cryptSL.Event}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Obj</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj</em>' reference list.
   * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getPreDefinedPredicates_Obj()
   * @model
   * @generated
   */
  EList<Event> getObj();

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(JvmType)
   * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getPreDefinedPredicates_Type()
   * @model
   * @generated
   */
  JvmType getType();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.cryptSL.PreDefinedPredicates#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(JvmType value);

} // PreDefinedPredicates
