/*
 * generated by Xtext 2.10.0
 */
package de.darmstadt.tu.crossing.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractCryptSLScopeProvider extends XbaseBatchScopeProvider {
}
