/**
 * generated by Xtext 2.21.0
 */
package de.darmstadt.tu.crossing.crySL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arithmetic Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.darmstadt.tu.crossing.crySL.CrySLPackage#getArithmeticExpression()
 * @model
 * @generated
 */
public interface ArithmeticExpression extends Constraint
{
} // ArithmeticExpression
