/**
 * generated by Xtext 2.21.0
 */
package de.darmstadt.tu.crossing.crySL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparing Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getLESS <em>LESS</em>}</li>
 *   <li>{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getLESS_OR_EQUAL <em>LESS OR EQUAL</em>}</li>
 *   <li>{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getGREATER_OR_EQUAL <em>GREATER OR EQUAL</em>}</li>
 *   <li>{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getGREATER <em>GREATER</em>}</li>
 *   <li>{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getEQUAL <em>EQUAL</em>}</li>
 *   <li>{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getUNEQUAL <em>UNEQUAL</em>}</li>
 * </ul>
 *
 * @see de.darmstadt.tu.crossing.crySL.CrySLPackage#getComparingOperator()
 * @model
 * @generated
 */
public interface ComparingOperator extends EObject
{
  /**
   * Returns the value of the '<em><b>LESS</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>LESS</em>' attribute.
   * @see #setLESS(String)
   * @see de.darmstadt.tu.crossing.crySL.CrySLPackage#getComparingOperator_LESS()
   * @model
   * @generated
   */
  String getLESS();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getLESS <em>LESS</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>LESS</em>' attribute.
   * @see #getLESS()
   * @generated
   */
  void setLESS(String value);

  /**
   * Returns the value of the '<em><b>LESS OR EQUAL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>LESS OR EQUAL</em>' attribute.
   * @see #setLESS_OR_EQUAL(String)
   * @see de.darmstadt.tu.crossing.crySL.CrySLPackage#getComparingOperator_LESS_OR_EQUAL()
   * @model
   * @generated
   */
  String getLESS_OR_EQUAL();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getLESS_OR_EQUAL <em>LESS OR EQUAL</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>LESS OR EQUAL</em>' attribute.
   * @see #getLESS_OR_EQUAL()
   * @generated
   */
  void setLESS_OR_EQUAL(String value);

  /**
   * Returns the value of the '<em><b>GREATER OR EQUAL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>GREATER OR EQUAL</em>' attribute.
   * @see #setGREATER_OR_EQUAL(String)
   * @see de.darmstadt.tu.crossing.crySL.CrySLPackage#getComparingOperator_GREATER_OR_EQUAL()
   * @model
   * @generated
   */
  String getGREATER_OR_EQUAL();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getGREATER_OR_EQUAL <em>GREATER OR EQUAL</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>GREATER OR EQUAL</em>' attribute.
   * @see #getGREATER_OR_EQUAL()
   * @generated
   */
  void setGREATER_OR_EQUAL(String value);

  /**
   * Returns the value of the '<em><b>GREATER</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>GREATER</em>' attribute.
   * @see #setGREATER(String)
   * @see de.darmstadt.tu.crossing.crySL.CrySLPackage#getComparingOperator_GREATER()
   * @model
   * @generated
   */
  String getGREATER();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getGREATER <em>GREATER</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>GREATER</em>' attribute.
   * @see #getGREATER()
   * @generated
   */
  void setGREATER(String value);

  /**
   * Returns the value of the '<em><b>EQUAL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>EQUAL</em>' attribute.
   * @see #setEQUAL(String)
   * @see de.darmstadt.tu.crossing.crySL.CrySLPackage#getComparingOperator_EQUAL()
   * @model
   * @generated
   */
  String getEQUAL();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getEQUAL <em>EQUAL</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>EQUAL</em>' attribute.
   * @see #getEQUAL()
   * @generated
   */
  void setEQUAL(String value);

  /**
   * Returns the value of the '<em><b>UNEQUAL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>UNEQUAL</em>' attribute.
   * @see #setUNEQUAL(String)
   * @see de.darmstadt.tu.crossing.crySL.CrySLPackage#getComparingOperator_UNEQUAL()
   * @model
   * @generated
   */
  String getUNEQUAL();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.crySL.ComparingOperator#getUNEQUAL <em>UNEQUAL</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>UNEQUAL</em>' attribute.
   * @see #getUNEQUAL()
   * @generated
   */
  void setUNEQUAL(String value);

} // ComparingOperator
