/**
 * generated by Xtext 2.21.0
 */
package de.darmstadt.tu.crossing.crySL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Imply</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.darmstadt.tu.crossing.crySL.LogicalImply#getIMPLIES <em>IMPLIES</em>}</li>
 * </ul>
 *
 * @see de.darmstadt.tu.crossing.crySL.CrySLPackage#getLogicalImply()
 * @model
 * @generated
 */
public interface LogicalImply extends EObject
{
  /**
   * Returns the value of the '<em><b>IMPLIES</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>IMPLIES</em>' attribute.
   * @see #setIMPLIES(String)
   * @see de.darmstadt.tu.crossing.crySL.CrySLPackage#getLogicalImply_IMPLIES()
   * @model
   * @generated
   */
  String getIMPLIES();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.crySL.LogicalImply#getIMPLIES <em>IMPLIES</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>IMPLIES</em>' attribute.
   * @see #getIMPLIES()
   * @generated
   */
  void setIMPLIES(String value);

} // LogicalImply
