/**
 * generated by Xtext 2.11.0
 */
package de.darmstadt.tu.crossing.cryptSL.impl;

import de.darmstadt.tu.crossing.cryptSL.CryptSLPackage;
import de.darmstadt.tu.crossing.cryptSL.Event;
import de.darmstadt.tu.crossing.cryptSL.ForbMethod;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.xtext.common.types.JvmOperation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Forb Method</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.darmstadt.tu.crossing.cryptSL.impl.ForbMethodImpl#getJavaMeth <em>Java Meth</em>}</li>
 *   <li>{@link de.darmstadt.tu.crossing.cryptSL.impl.ForbMethodImpl#getRep <em>Rep</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ForbMethodImpl extends MinimalEObjectImpl.Container implements ForbMethod
{
  /**
   * The cached value of the '{@link #getJavaMeth() <em>Java Meth</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJavaMeth()
   * @generated
   * @ordered
   */
  protected JvmOperation javaMeth;

  /**
   * The cached value of the '{@link #getRep() <em>Rep</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRep()
   * @generated
   * @ordered
   */
  protected Event rep;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForbMethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CryptSLPackage.Literals.FORB_METHOD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JvmOperation getJavaMeth()
  {
    if (javaMeth != null && javaMeth.eIsProxy())
    {
      InternalEObject oldJavaMeth = (InternalEObject)javaMeth;
      javaMeth = (JvmOperation)eResolveProxy(oldJavaMeth);
      if (javaMeth != oldJavaMeth)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CryptSLPackage.FORB_METHOD__JAVA_METH, oldJavaMeth, javaMeth));
      }
    }
    return javaMeth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JvmOperation basicGetJavaMeth()
  {
    return javaMeth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setJavaMeth(JvmOperation newJavaMeth)
  {
    JvmOperation oldJavaMeth = javaMeth;
    javaMeth = newJavaMeth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CryptSLPackage.FORB_METHOD__JAVA_METH, oldJavaMeth, javaMeth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Event getRep()
  {
    if (rep != null && rep.eIsProxy())
    {
      InternalEObject oldRep = (InternalEObject)rep;
      rep = (Event)eResolveProxy(oldRep);
      if (rep != oldRep)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CryptSLPackage.FORB_METHOD__REP, oldRep, rep));
      }
    }
    return rep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Event basicGetRep()
  {
    return rep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRep(Event newRep)
  {
    Event oldRep = rep;
    rep = newRep;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CryptSLPackage.FORB_METHOD__REP, oldRep, rep));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CryptSLPackage.FORB_METHOD__JAVA_METH:
        if (resolve) return getJavaMeth();
        return basicGetJavaMeth();
      case CryptSLPackage.FORB_METHOD__REP:
        if (resolve) return getRep();
        return basicGetRep();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CryptSLPackage.FORB_METHOD__JAVA_METH:
        setJavaMeth((JvmOperation)newValue);
        return;
      case CryptSLPackage.FORB_METHOD__REP:
        setRep((Event)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CryptSLPackage.FORB_METHOD__JAVA_METH:
        setJavaMeth((JvmOperation)null);
        return;
      case CryptSLPackage.FORB_METHOD__REP:
        setRep((Event)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CryptSLPackage.FORB_METHOD__JAVA_METH:
        return javaMeth != null;
      case CryptSLPackage.FORB_METHOD__REP:
        return rep != null;
    }
    return super.eIsSet(featureID);
  }

} //ForbMethodImpl
