/**
 * generated by Xtext 2.10.0
 */
package de.darmstadt.tu.crossing;

import de.darmstadt.tu.crossing.AbstractCryptSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CryptSLRuntimeModule extends AbstractCryptSLRuntimeModule {
}
