/*
 * generated by Xtext 2.27.0
 */
package de.darmstadt.tu.crossing;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CrySLStandaloneSetup extends CrySLStandaloneSetupGenerated {

	public static void doSetup() {
		new CrySLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
